
{
"name": "Simplicity Bookcase with 3 shelves",
"shipping weight": #,
"actual weight": #,
"color": "",
"# of cartons": #,
"packing width":#,
"pakcing depth":#,
"pakcing height": #,
"actual width": #,
"actual width": #,
"actual height": #,
"shelf length": #,
"shelf width": #,
"inches between shelf": #,
"material": "",
"product description": "",
"product specification": "",
"feature 1": "",
"feature 2": "",
"feature 3": "",
"care instructions": "",
"assembly required": "",
"whoesale price": #,
"retail price": #
},
{
  "name": "Simplicity Bookcase with 4 Shelves",
  "shipping weight": #,
  "actual weight": #,
  "color": "",
  "# of cartons": #,
  "packing width":#,
  "pakcing depth":#,
  "pakcing height": #,
  "actual width": #,
  "actual width": #,
  "actual height": #,
  "shelf length": #,
  "shelf width": #,
  "inches between shelf": #,
  "material": "",
  "product description": "",
  "product specification": "",
  "feature 1": "",
  "feature 2": "",
  "feature 3": "",
  "care instructions": "",
  "assembly required": "",
  "whoesale price": #,
  "retail price": #
},
{
  "name": "Simplicity Storage Cabinet with 3 Doors 3 Drawers",
  "shipping weight": #,
  "actual weight": #,
  "color": "",
  "# of cartons": #,
  "packing width":#,
  "pakcing depth":#,
  "pakcing height": #,
  "actual width": #,
  "actual width": #,
  "actual height": #,
  "shelf length": #,
  "shelf width": #,
  "inches between shelf": #,
  "material": "",
  "product description": "",
  "product specification": "",
  "feature 1": "",
  "feature 2": "",
  "feature 3": "",
  "care instructions": "",
  "assembly required": "",
  "whoesale price": #,
  "retail price": #
}
